version: '3'
networks:
 network1:
  
  
services:
  nginx:
   image: webdevops/php-nginx:8.0
   container_name: nginx_currency_project
   restart: unless-stopped
   depends_on:
   - mysql
   ports:
   - "8080:80"
   volumes:
   - ./laravel_project:/app
   - ./vhost_config/vhost.conf:/opt/docker/etc/nginx/vhost.conf
   networks:
    - network1

  mysql:
   image: mysql:8.0
   container_name: mysql_currency_project
   restart: unless-stopped
   tty: true
   ports:
   - "3309:3306"
   volumes:
   - ./mysql_data:/var/lib/mysql
   environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}   
   networks:
    - network1
   

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:5.0
    restart: always
    ports:
      - 8081:80
    networks:
      - network1
    environment:
      - PMA_ARBITRARY=1

  
volumes:
  mysql_data:
    driver: local